[build-system]
requires = [
    "setuptools>=61", "wheel"
 ]
build-backend = "setuptools.build_meta"

[project]
name = "statcodgen"
version = "1.0.0"
description = "Library for training an autoencoder and generate synt data."

readme = {file = "README.md", content-type = "text/markdown"}

authors = [
    {name = "Methodology unit (INE)", email = "git.metodologia@ine.es"},
]

license = {text = "EUPL European Public License"}

dependencies = [
    'pandas',
    'numpy==1.26.2',
    'SPARQLWrapper',
    'fasttext',
    'openpyxl',
    'matplotlib',
    'scikit-learn',
    'nltk',
    'xlrd',
    'requests',
    'httpx',
    "transformers==4.37.1",
    "tokenizers==0.15.1",
    "accelerate==0.25.0",
    "huggingface-hub>=0.19.3,<1.0",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]


[project.optional-dependencies]
api = ["groq", "httpx"]
tests = ["pytest"]



[project.urls]
Homepage = 'https://github.com/AIML4OS/WP10_Cluster1_StatCodGen'

[tool.setuptools.packages.find]
where = ["."]
include = ["statcodgen*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v --tb=short"
markers = [
    "unit: fast unit test without I/O",
    "integration:  test with I/O",
    "slow: slow test (exclude with -m 'not slow')",
]
